version: '3'

services:
    gitlab:
        image: gitlab/gitlab-ce
        container_name: "gitlab"
        restart: always
        ports:
        - "80:80"
        - "443:443"
        - "10022:22"
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://gitlab.csys.me'
                gitlab_rails['gitlab_shell_ssh_port'] = 10022
        volumes:
        - '/srv/gitlab/etc:/etc/gitlab'
        - '/srv/gitlab/logs:/var/log/gitlab'
        - '/srv/gitlab/data:/var/opt/gitlab'
networks:
  default:
    driver: bridge